build: false

environment:
    matrix:
        - PYTHON: "C:\\Python38"
        - PYTHON: "C:\\Python39"
        - PYTHON: "C:\\Python310"
        - PYTHON: "C:\\Python311"
        - PYTHON: "C:\\Python38-x64"
        - PYTHON: "C:\\Python39-x64"
        - PYTHON: "C:\\Python310-x64"
        - PYTHON: "C:\\Python311-x64"
        
matrix:
    allow_failures:
        # Until 3.9-11 is supported in appveyor.
        - PYTHON: "C:\\Python39"
        - PYTHON: "C:\\Python39-x64"
        - PYTHON: "C:\\Python310"
        - PYTHON: "C:\\Python310-x64"
        - PYTHON: "C:\\Python311"
        - PYTHON: "C:\\Python311-x64"

init:
  - SET PATH=%PYTHON%;%PATH%

install:
    - python -m pip install -r requirements_dev.txt
    - python -m pip install -r requirements.txt

test_script:
    - python -m pytest
