language: python

os:
    - linux
    - windows


cache: pip

python:
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"
    - "nightly"


matrix:
    fast_finish: true
    allow_failures:
        - os: windows  # allow failure on Win until Travis-Win supports python.
        - python: "nightly"

install:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt


# command to run tests
script:
    - pytest --cov --mypy

after_success: coveralls
